- hosts: manager

  tasks:

    - name: Create a 'proxy' network
      local_action: shell docker network create --driver=overlay proxy
      ignore_errors: yes

    - name: secrets
      local_action: >
        shell echo "user" | docker secret create dfp_stats_user - && \
        echo "pass" | docker secret create dfp_stats_pass -
      ignore_errors: yes

    - name: deploy stack 'docker-flow-proxy'
      local_action: shell docker stack deploy --compose-file ./docker/docker-flow-proxy.yml proxy

    - name: deploy stack 'stack-hello-world'
      local_action: shell docker stack deploy --compose-file ./docker/stack-hello-world.yml hello-world
