
- hosts: all
  gather_facts: false
  connection: local

  tasks:

  - name: accept new ssh fingerprints
    shell: ssh-keyscan -t rsa {{ item }} >> ~/.ssh/known_hosts
    with_items: "{{ hostvars[inventory_hostname]['ansible_host'] }}"




- hosts: all
  gather_facts: false

  tasks:

  # ubuntu16.04 doesn't come with the correct python
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  - name: apt | make sure the required packages are installed
    apt:
      pkg: "{{ item }}"
      state: present
    with_items:
      - python-pip
      - python-dev
      - build-essential

  # https://github.com/docker/docker-py
  - name: install docker python module
    pip:
      name: "{{ item }}"
      state: present
    with_items:
      - docker-compose
      - docker


- hosts: all
  connection: local
  gather_facts: false

  tasks:

  - name: docker-machine upgrade
    shell: "docker-machine upgrade {{ inventory_hostname }}"

