version: '3.1'

services:

  main:
    image: vfarcic/go-demo
    environment:
      - DB=db
    networks:
      - proxy
      - hello-world
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=hello-world.bushbaby.nl
        - com.df.port=8080

  db:
    image: mongo
    networks:
      - hello-world

networks:
  hello-world:
    external: false
  proxy:
    external: true
